x-common-config: &common-config
  build:
    context: .
    dockerfile: Dockerfile
  user: "0:0"
  environment:
    HOME: /root
  volumes:
    - ~/.nanobot:/root/.nanobot
    - /root/nanobot-src:/root/nanobot-src

services:
  nanobot-gateway:
    container_name: nanobot-gateway
    <<: *common-config
    command: ["gateway", "--foreground"]
    restart: unless-stopped
    ports:
      - 18790:18790
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G
        reservations:
          cpus: '0.25'
          memory: 256M

  nanobot-cli:
    <<: *common-config
    profiles:
      - cli
    command: ["status"]
    stdin_open: true
    tty: true
